import { DBExams } from '../utils/interfaces';

export const exams: DBExams[] = [
  {
    title: 'Examen de conciencia para adultos',
    content:
      " - ¿Creo todo lo que Dios ha revelado y nos enseña la Iglesia Católica? ¿He dudado o negado las verdades de la fe católica? {'\n'} - ¿Hago con desgana las cosas que se refieren a Dios? ¿Me acuerdo del Señor a lo largo del día? ¿Rezo en algún momento de la jornada? {'\n'} - ¿He recibido al Señor en la Sagrada Comunión teniendo algún pecado grave en mi conciencia? ¿He callado en la confesión por vergüenza algún pecado mortal? {'\n'} - ¿He blasfemado? ¿He jurado sin necesidad o sin verdad? ¿He practicado la superstición o el espiritismo? {'\n'} - ¿He faltado a Misa los domingos o días festivos? ¿He cumplido los días de ayuno y abstinencia? {'\n'} … y al prójimo como a ti mismo. {'\n'} - ¿Manifiesto respeto y cariño a mis familiares? ¿estoy pendiente y ayudo en el cuidado de mis padres o familiares si lo necesitan? ¿Soy amable con los extraños y me falta esa amabilidad en la vida de familia? ¿tengo paciencia? {'\n'} - ¿Permito que mi trabajo ocupe tiempo y energías que corresponden a mi familia o amigos? Si estoy casado, ¿he fortalecido la autoridad de mi cónyuge, evitando reprenderle, contradecirle o discutirle delante de los hijos? {'\n'} - ¿Respeto la vida humana? ¿He cooperado o alentado a alguien a abortar, destruir embriones, a la eutanasia o cualquier otro medio que atente contra la vida de seres humanos? {'\n'} - ¿Deseo el bien a los demás, o albergo odios y realizo juicios críticos? ¿He sido violento verbal o físicamente en familia, en el trabajo o en otros ambientes? ¿He dado mal ejemplo a las personas que me rodean? ¿Les corrijo con cólera o injustamente? {'\n'} - ¿Procuro cuidar mi salud? ¿He tomado alcohol en exceso? ¿He tomado drogas? ¿He arriesgado mi vida injustificadamente (por el modo de conducir, las diversiones, etc.)? {'\n'} - ¿He mirado vídeos o páginas web pornográficas? ¿Incito a otros a hacer el mal? {'\n'} - ¿Vivo la castidad? ¿He cometido actos impuros conmigo mismo o con otras personas? ¿He consentido pensamientos, deseos o sensaciones impuras? ¿Vivo con alguien como si estuviéramos casados sin estarlo? {'\n'} - Si estoy casado, ¿he cuidado la fidelidad matrimonial? ¿procuro amar a mi cónyuge por encima de cualquier otra persona? ¿Pongo mi matrimonio y mis hijos en primer lugar? ¿Tengo una actitud abierta a nuevas vidas? {'\n'} - ¿He tomado dinero o cosas que no son mías? ¿En su caso, he restituido o reparado? {'\n'} - ¿Procuro cumplir con mis deberes profesionales? ¿Soy honesto? ¿He engañado a otros: cobrando más de lo debido, ofreciendo a propósito un servicio defectuoso? {'\n'} - ¿He gastado dinero para mi comodidad o lujo personal olvidando mis responsabilidades hacia otros y hacia la Iglesia? ¿He desatendido a los pobres o a los necesitados? ¿Cumplo con mis deberes de ciudadano? {'\n'} - ¿He dicho mentiras? ¿He reparado el daño que haya podido seguirse? ¿He descubierto, sin causa justa, defectos graves de otras personas? ¿He hablado o pensado mal de otros? ¿He calumniado?",
  },
];
