import { DBExams } from '../utils/interfaces';

export const exams: DBExams[] = [
  {
    title: 'Examen de conciencia para adultos',
    content:
      ' - ¿Creo todo lo que Dios ha revelado y nos enseña la Iglesia Católica? ¿He dudado o negado las verdades de la fe católica?  - ¿Hago con desgana las cosas que se refieren a Dios? ¿Me acuerdo del Señor a lo largo del día? ¿Rezo en algún momento de la jornada?  - ¿He recibido al Señor en la Sagrada Comunión teniendo algún pecado grave en mi conciencia? ¿He callado en la confesión por vergüenza algún pecado mortal?  - ¿He blasfemado? ¿He jurado sin necesidad o sin verdad? ¿He practicado la superstición o el espiritismo?  - ¿He faltado a Misa los domingos o días festivos? ¿He cumplido los días de ayuno y abstinencia?  … y al prójimo como a ti mismo.  - ¿Manifiesto respeto y cariño a mis familiares? ¿estoy pendiente y ayudo en el cuidado de mis padres o familiares si lo necesitan? ¿Soy amable con los extraños y me falta esa amabilidad en la vida de familia? ¿tengo paciencia?  - ¿Permito que mi trabajo ocupe tiempo y energías que corresponden a mi familia o amigos? Si estoy casado, ¿he fortalecido la autoridad de mi cónyuge, evitando reprenderle, contradecirle o discutirle delante de los hijos?  - ¿Respeto la vida humana? ¿He cooperado o alentado a alguien a abortar, destruir embriones, a la eutanasia o cualquier otro medio que atente contra la vida de seres humanos?  - ¿Deseo el bien a los demás, o albergo odios y realizo juicios críticos? ¿He sido violento verbal o físicamente en familia, en el trabajo o en otros ambientes? ¿He dado mal ejemplo a las personas que me rodean? ¿Les corrijo con cólera o injustamente?  - ¿Procuro cuidar mi salud? ¿He tomado alcohol en exceso? ¿He tomado drogas? ¿He arriesgado mi vida injustificadamente (por el modo de conducir, las diversiones, etc.)?  - ¿He mirado vídeos o páginas web pornográficas? ¿Incito a otros a hacer el mal?  - ¿Vivo la castidad? ¿He cometido actos impuros conmigo mismo o con otras personas? ¿He consentido pensamientos, deseos o sensaciones impuras? ¿Vivo con alguien como si estuviéramos casados sin estarlo?  - Si estoy casado, ¿he cuidado la fidelidad matrimonial? ¿procuro amar a mi cónyuge por encima de cualquier otra persona? ¿Pongo mi matrimonio y mis hijos en primer lugar? ¿Tengo una actitud abierta a nuevas vidas?  - ¿He tomado dinero o cosas que no son mías? ¿En su caso, he restituido o reparado?  - ¿Procuro cumplir con mis deberes profesionales? ¿Soy honesto? ¿He engañado a otros: cobrando más de lo debido, ofreciendo a propósito un servicio defectuoso?  - ¿He gastado dinero para mi comodidad o lujo personal olvidando mis responsabilidades hacia otros y hacia la Iglesia? ¿He desatendido a los pobres o a los necesitados? ¿Cumplo con mis deberes de ciudadano?  - ¿He dicho mentiras? ¿He reparado el daño que haya podido seguirse? ¿He descubierto, sin causa justa, defectos graves de otras personas? ¿He hablado o pensado mal de otros? ¿He calumniado?',
  },
  {
    title: 'Examen de conciencia para jovenes',
    content:
      '- ¿He rechazado o abandonado mi fe? - ¿Me he preocupado por conocerla mejor? - ¿La he defendido, o me he avergonzado de ella? - ¿He tomado el nombre de Dios en vano? - ¿He hecho espiritismo o he confiado en adivinos u horóscopos? - ¿He mostrado falta de respeto por las personas, lugares o cosas santas? - ¿He faltado voluntariamente a la Santa Misa los domingos o días de precepto? - ¿Me he olvidado de Dios abandonando mis oraciones? - ¿He recibido al Señor en la Sagrada Comunión teniendo algún pecado grave en mi conciencia? - ¿Le he recibido sin agradecimiento o sin la debida reverencia? - ¿He ayudado poco en casa? - ¿He tra-tado con poco cariño a mis padres? - ¿He sido impaciente, envidioso? - ¿Me he enfadado? - ¿He fomentado el resentimiento o no he estado dispuesto a perdonar? - ¿He odiado a alguien o le he juzgado mal? - ¿He descuidado mis deberes de estudiante? - ¿He sido perezoso? - ¿He tratado con falta de respeto a mis profesores o a otras personas mayores? - ¿Me he peleado? - ¿He hecho daño a alguien con insultos o hablando mal de ellos? - ¿He revelado algún secreto o he dicho cosas solo para dañar aotros? - ¿He dicho o he pensado cosas impuras? - ¿Las he hecho conmigo mismo o con otros? - ¿He mirado imágenes o películas pornográficas? - ¿He dicho mentiras para justificarme, dañar a otros o por darme más importancia? - ¿He robado algo? - ¿He estropeado algo a propósito? - ¿He tenido envidia de otros por lo que tienen o por el buen resultado de su trabajo? - ¿Pongo mi corazón en tener cosas? - ¿He ayudado o fomentado que otros hagan el mal? - ¿He tomado alcohol en exceso? - ¿He consumido drogas? - ¿He sido egoísta de pensamiento o de obra? - ¿He preferido mi comodidad al servicio a los demás? - ¿He desatendido mi responsabilidad de acercar a los demás a Dios con mi ejemplo y mi palabra?',
  },
  {
    title: 'Examen de conciencia para niños',
    content:
      '- ¿He rezado mis oraciones? - ¿He ido a Misa los Domingos? - ¿He tomado el nombre de Dios en vano? - ¿Me he distraído voluntariamente en Misa o en la Iglesia? - ¿He ayudado en casa? - ¿He sido egoísta o he tratado a mis padres y hermanos con poco cariño? - ¿He obedecido a mis padres y profesores? - ¿He compartido mis juguetes con los demás? - ¿He sido impaciente? - ¿Me he enfadado? - ¿He sido caprichoso o pesado para que las cosas se hicieran como yo quiero? - ¿Pierdo el tiempo en clase? - ¿He hecho mis deberes lo mejor que puedo? - ¿He copiado en los exámenes? - ¿Me he peleado? - ¿He hecho daño a alguna persona hablando mal de ella? - ¿He dicho mentiras? - ¿He robado algo? - ¿He estropeado alguna cosa que no era mía a propósito? - ¿He dado buen ejemplo? - ¿He animado a otros a que hicieran cosas malas? - ¿He sido egoísta de pensamiento o de obra? - ¿He tenido celos de otros? - ¿He excluido a alguien de mis juegos? - ¿He rezado por los demás y les he ayudado para que estén más cerca de Dios?',
  },
];
