import { DBExams } from '../utils/interfaces';

export const exams: DBExams[] = [
  {
    title: 'Examen de conciencia para adultos',
    content:
      '- ¿Creo todo lo que Dios ha revelado y nos enseña la Iglesia Católica? ¿He dudado o negado las verdades de la fe católica?  \n\n - ¿Hago con desgana las cosas que se refieren a Dios? ¿Me acuerdo del Señor a lo largo del día? ¿Rezo en algún momento de la jornada?  \n\n - ¿He recibido al Señor en la Sagrada Comunión teniendo algún pecado grave en mi conciencia? ¿He callado en la confesión por vergüenza algún pecado mortal?  \n\n - ¿He blasfemado? ¿He jurado sin necesidad o sin verdad? ¿He practicado la superstición o el espiritismo?  \n\n - ¿He faltado a Misa los domingos o días festivos? ¿He cumplido los días de ayuno y abstinencia?  … y al prójimo como a ti mismo.  \n\n - ¿Manifiesto respeto y cariño a mis familiares? ¿estoy pendiente y ayudo en el cuidado de mis padres o familiares si lo necesitan? ¿Soy amable con los extraños y me falta esa amabilidad en la vida de familia? ¿tengo paciencia?  \n\n - ¿Permito que mi trabajo ocupe tiempo y energías que corresponden a mi familia o amigos? Si estoy casado, ¿he fortalecido la autoridad de mi cónyuge, evitando reprenderle, contradecirle o discutirle delante de los hijos?  \n\n - ¿Respeto la vida humana? ¿He cooperado o alentado a alguien a abortar, destruir embriones, a la eutanasia o cualquier otro medio que atente contra la vida de seres humanos?  \n\n - ¿Deseo el bien a los demás, o albergo odios y realizo juicios críticos? ¿He sido violento verbal o físicamente en familia, en el trabajo o en otros ambientes? ¿He dado mal ejemplo a las personas que me rodean? ¿Les corrijo con cólera o injustamente?  \n\n - ¿Procuro cuidar mi salud? ¿He tomado alcohol en exceso? ¿He tomado drogas? ¿He arriesgado mi vida injustificadamente (por el modo de conducir, las diversiones, etc.)?  \n\n - ¿He mirado vídeos o páginas web pornográficas? ¿Incito a otros a hacer el mal?  \n\n - ¿Vivo la castidad? ¿He cometido actos impuros conmigo mismo o con otras personas? ¿He consentido pensamientos, deseos o sensaciones impuras? ¿Vivo con alguien como si estuviéramos casados sin estarlo?  \n\n - Si estoy casado, ¿he cuidado la fidelidad matrimonial? ¿procuro amar a mi cónyuge por encima de cualquier otra persona? ¿Pongo mi matrimonio y mis hijos en primer lugar? ¿Tengo una actitud abierta a nuevas vidas?  \n\n - ¿He tomado dinero o cosas que no son mías? ¿En su caso, he restituido o reparado?  \n\n - ¿Procuro cumplir con mis deberes profesionales? ¿Soy honesto? ¿He engañado a otros: cobrando más de lo debido, ofreciendo a propósito un servicio defectuoso?  \n\n - ¿He gastado dinero para mi comodidad o lujo personal olvidando mis responsabilidades hacia otros y hacia la Iglesia? ¿He desatendido a los pobres o a los necesitados? ¿Cumplo con mis deberes de ciudadano?  \n\n - ¿He dicho mentiras? ¿He reparado el daño que haya podido seguirse? ¿He descubierto, sin causa justa, defectos graves de otras personas? ¿He hablado o pensado mal de otros? ¿He calumniado?',
  },
  {
    title: 'Examen de conciencia para jovenes',
    content:
      '- ¿He rechazado o abandonado mi fe? \n\n - ¿Me he preocupado por conocerla mejor? \n\n - ¿La he defendido, o me he avergonzado de ella? \n\n - ¿He tomado el nombre de Dios en vano? \n\n - ¿He hecho espiritismo o he confiado en adivinos u horóscopos? \n\n - ¿He mostrado falta de respeto por las personas, lugares o cosas santas? \n\n - ¿He faltado voluntariamente a la Santa Misa los domingos o días de precepto? \n\n - ¿Me he olvidado de Dios abandonando mis oraciones? \n\n - ¿He recibido al Señor en la Sagrada Comunión teniendo algún pecado grave en mi conciencia? \n\n - ¿Le he recibido sin agradecimiento o sin la debida reverencia? \n\n - ¿He ayudado poco en casa? \n\n - ¿He tra\n\n -tado con poco cariño a mis padres? \n\n - ¿He sido impaciente, envidioso? \n\n - ¿Me he enfadado? \n\n - ¿He fomentado el resentimiento o no he estado dispuesto a perdonar? \n\n - ¿He odiado a alguien o le he juzgado mal? \n\n - ¿He descuidado mis deberes de estudiante? \n\n - ¿He sido perezoso? \n\n - ¿He tratado con falta de respeto a mis profesores o a otras personas mayores? \n\n - ¿Me he peleado? \n\n - ¿He hecho daño a alguien con insultos o hablando mal de ellos? \n\n - ¿He revelado algún secreto o he dicho cosas solo para dañar aotros? \n\n - ¿He dicho o he pensado cosas impuras? \n\n - ¿Las he hecho conmigo mismo o con otros? \n\n - ¿He mirado imágenes o películas pornográficas? \n\n - ¿He dicho mentiras para justificarme, dañar a otros o por darme más importancia? \n\n - ¿He robado algo? \n\n - ¿He estropeado algo a propósito? \n\n - ¿He tenido envidia de otros por lo que tienen o por el buen resultado de su trabajo? \n\n - ¿Pongo mi corazón en tener cosas? \n\n - ¿He ayudado o fomentado que otros hagan el mal? \n\n - ¿He tomado alcohol en exceso? \n\n - ¿He consumido drogas? \n\n - ¿He sido egoísta de pensamiento o de obra? \n\n - ¿He preferido mi comodidad al servicio a los demás? \n\n - ¿He desatendido mi responsabilidad de acercar a los demás a Dios con mi ejemplo y mi palabra?',
  },
  {
    title: 'Examen de conciencia para niños',
    content:
      '- ¿He rezado mis oraciones? \n\n - ¿He ido a Misa los Domingos? \n\n - ¿He tomado el nombre de Dios en vano? \n\n - ¿Me he distraído voluntariamente en Misa o en la Iglesia? \n\n - ¿He ayudado en casa? \n\n - ¿He sido egoísta o he tratado a mis padres y hermanos con poco cariño? \n\n - ¿He obedecido a mis padres y profesores? \n\n - ¿He compartido mis juguetes con los demás? \n\n - ¿He sido impaciente? \n\n - ¿Me he enfadado? \n\n - ¿He sido caprichoso o pesado para que las cosas se hicieran como yo quiero? \n\n - ¿Pierdo el tiempo en clase? \n\n - ¿He hecho mis deberes lo mejor que puedo? \n\n - ¿He copiado en los exámenes? \n\n - ¿Me he peleado? \n\n - ¿He hecho daño a alguna persona hablando mal de ella? \n\n - ¿He dicho mentiras? \n\n - ¿He robado algo? \n\n - ¿He estropeado alguna cosa que no era mía a propósito? \n\n - ¿He dado buen ejemplo? \n\n - ¿He animado a otros a que hicieran cosas malas? \n\n - ¿He sido egoísta de pensamiento o de obra? \n\n - ¿He tenido celos de otros? \n\n - ¿He excluido a alguien de mis juegos? \n\n - ¿He rezado por los demás y les he ayudado para que estén más cerca de Dios?',
  },
];
