name: CI

on:
  push:
    branches: ['master', 'dev']
  pull_request:
    branches: ['master', 'dev']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          yarn
          yarn cov
          curl -Os https://uploader.codecov.io/latest/linux/codecov; chmod +x codecov; ./codecov -t ${{ secrets.CODECOV_TOKEN }}
