name: CI

on:
  push:
    branches: ['master', 'dev']
  pull_request:
    branches: ['master', 'dev']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          yarn
          yarn test
